language: csharp
mono: none
dotnet: 3.1
os:
  - linux

sudo: required
dist: trusty

git:
  depth: false

deploy:
  - provider: script
    script: ./build.sh push --NugetApiKey $NUGET_API_KEY --configuration Release
    on:
      branch: master
      tags: true
  - provider: script
    script: ./build.sh push --NugetApiKey $NUGET_API_KEY --configuration Debug
    on:
      tags: false
      all_branches: true
