language: csharp
mono: none
dotnet: 3.1
os:
  - osx
  - linux

sudo: required
dist: trusty

addons:
  apt:
    sources:
      - sourceline: 'deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main'
        key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
    packages:
      - gettext
      - libcurl4-openssl-dev
      - libicu-dev
      - libssl-dev
      - libunwind8

git:
  depth: false

deploy:
  - provider: script
    script: ./build.sh push --NugetApiKey $NUGET_API_KEY --configuration Release
    on:
      branch: master
      tags: true
  - provider: script
    script: ./build.sh push --NugetApiKey $NUGET_API_KEY --configuration Debug
    on:
      tags: false
      all_branches: true
